"""
This type stub file was generated by pyright.
"""

from translator.base import TranslationResult, Translator

"""Заглушка сервиса перевода.

Используется до подключения реального внешнего сервиса-переводчика.
"""
class StubTranslator(Translator):
    """Возвращает фиктивный перевод, не обращаясь к внешним сервисам."""
    async def translate(self, text: str, source_lang: str = ..., target_lang: str = ...) -> TranslationResult:
        ...
    


