"""
This type stub file was generated by pyright.
"""

from .auth import router as auth_router
from .main import app
from .words import router as words_router

"""Роутеры API приложения."""
__all__ = ["auth_router", "words_router", "app"]
