"""
This type stub file was generated by pyright.
"""

from database.models import User
from fastapi import status
from schemas.auth import LoginRequest, RegisterRequest, TokenResponse, UserResponse
from sqlalchemy.ext.asyncio import AsyncSession

"""Роутер аутентификации: регистрация, авторизация, текущий пользователь."""
router = ...
@router.post("/register", response_model=TokenResponse, status_code=status.HTTP_201_CREATED)
async def register(payload: RegisterRequest, db: AsyncSession = ...) -> TokenResponse:
    """Зарегистрировать нового пользователя и вернуть JWT-токен."""
    ...

@router.post("/login", response_model=TokenResponse)
async def login(payload: LoginRequest, db: AsyncSession = ...) -> TokenResponse:
    """Авторизовать пользователя по email и паролю."""
    ...

@router.get("/me", response_model=UserResponse)
async def me(current_user: User = ...) -> User:
    """Вернуть данные текущего пользователя."""
    ...

