"""
This type stub file was generated by pyright.
"""

"""Главная точка входа приложения FastAPI."""
app = ...
@app.get("/")
async def root() -> dict[str, str]:
    """Корневой эндпоинт для проверки работоспособности."""
    ...

if __name__ == "__main__":
    ...
