"""
This type stub file was generated by pyright.
"""

from database.models import User, Word
from fastapi import status
from schemas.words import WordCreateRequest, WordResponse
from sqlalchemy.ext.asyncio import AsyncSession

"""Роутер слов: запись, просмотр и удаление слов пользователя."""
router = ...
@router.post("", response_model=WordResponse, status_code=status.HTTP_201_CREATED)
async def create_word(payload: WordCreateRequest, current_user: User = ..., db: AsyncSession = ...) -> Word:
    """Добавить слово, получив перевод через сервис-переводчик (заглушка)."""
    ...

@router.get("", response_model=list[WordResponse])
async def list_words(current_user: User = ..., db: AsyncSession = ...) -> list[Word]:
    """Вернуть список слов текущего пользователя."""
    ...

@router.get("/{word_id}", response_model=WordResponse)
async def get_word(word_id: int, current_user: User = ..., db: AsyncSession = ...) -> Word:
    """Вернуть одно слово текущего пользователя."""
    ...

@router.delete("/{word_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_word(word_id: int, current_user: User = ..., db: AsyncSession = ...) -> None:
    """Удалить слово текущего пользователя."""
    ...

