"""
This type stub file was generated by pyright.
"""

from database.models import User
from fastapi.security import HTTPAuthorizationCredentials
from sqlalchemy.ext.asyncio import AsyncSession

"""FastAPI-зависимости для аутентификации."""
bearer_scheme = ...
async def get_current_user(credentials: HTTPAuthorizationCredentials | None = ..., db: AsyncSession = ...) -> User:
    """Вернуть текущего пользователя по JWT-токену из заголовка Authorization."""
    ...

