"""
This type stub file was generated by pyright.
"""

"""Безопасность: хэширование паролей и работа с JWT-токенами."""
def hash_password(password: str) -> str:
    """Хэшировать пароль с помощью bcrypt."""
    ...

def verify_password(password: str, hashed: str) -> bool:
    """Проверить пароль против bcrypt-хэша."""
    ...

def create_access_token(user_id: int) -> str:
    """Создать JWT-токен доступа для пользователя."""
    ...

def decode_access_token(token: str) -> int:
    """Декодировать JWT-токен и вернуть user_id.

    Raises:
        jwt.PyJWTError: если токен невалиден или просрочен.
    """
    ...

