"""
This type stub file was generated by pyright.
"""

from .auth import LoginRequest, RegisterRequest, TokenResponse, UserResponse
from .words import WordCreateRequest, WordResponse

"""Pydantic-схемы приложения."""
__all__ = ["LoginRequest", "RegisterRequest", "TokenResponse", "UserResponse", "WordCreateRequest", "WordResponse"]
