"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel, EmailStr

"""Pydantic-схемы для аутентификации и пользователей."""
class RegisterRequest(BaseModel):
    """Данные для регистрации нового пользователя."""
    nickname: str = ...
    email: EmailStr
    password: str = ...
    telegram_nickname: str | None = ...


class LoginRequest(BaseModel):
    """Данные для входа в систему."""
    email: EmailStr
    password: str
    ...


class UserResponse(BaseModel):
    """Публичные данные пользователя."""
    id: int
    nickname: str
    email: str
    telegram_nickname: str | None
    model_config = ...


class TokenResponse(BaseModel):
    """Ответ с JWT-токеном доступа."""
    access_token: str
    token_type: str = ...


