"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from pydantic import BaseModel

"""Pydantic-схемы для слов."""
class WordCreateRequest(BaseModel):
    """Данные для добавления слова."""
    word_en: str = ...


class WordResponse(BaseModel):
    """Слово с переводом."""
    id: int
    word_en: str
    translation: str | None
    created_at: datetime
    model_config = ...


